# Generated by Django 6.0.6 on 2026-06-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_created_at_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='unanswered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
