# Generated by Django 6.0.6 on 2026-06-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
