# Generated by Django 6.0.6 on 2026-06-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_delete_subject'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicclass'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.section'),
        ),
        migrations.DeleteModel(
            name='AcademicClass',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
