# Generated by Django 6.0.6 on 2026-07-02 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='motivation_videos/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateField()),
                ('target_class', models.CharField(choices=[('ALL', 'All Students'), ('1-5', 'Class 1-5'), ('6-8', 'Class 6-8'), ('9-10', 'Class 9-10'), ('11-12', 'Class 11-12')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('camera_enabled', models.BooleanField(default=False)),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motivation.motivationvideo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'motivation')},
            },
        ),
    ]
